# ----PROMPT-----#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

# Step 1. make the fibonacci sequence array

ARRAY = [0]
MAX = 4000000
def fibonacci
  number_1 = 1
  number_2 = 0

  while ARRAY.max < MAX do
    current = number_1+number_2
    ARRAY.push(current)
    number_2 = number_1
    number_1 = current
  end
end

# Don't forget to call it
fibonacci

# make the evens only method
def evens_only
  sum = 0
  ARRAY.map do |number|
    if number%2 == 0 && number < MAX
      sum += number
    end
  end
  print sum
end

evens_only
